### PR TITLE
fix isObject

### PR DESCRIPTION
**Pull request by jareddlc**
I was trying to use the `fleetctl.start()` function which would fail, when not providing with a options parameter. I looked into what was causing the issue and it seems like the `lodash.isObject()` evaluates a function to be true, which in turn causes it the logic to execute incorrectly and callback an undefined variable.

Changing the order of evaluating is a quick fix, but may not be the best solution.  Please test to make sure this PR does not break any other features, as I have only tested it with `fleetctl.start()`.

I know this is not the `lodash` module, but I encountered similar issue.  https://github.com/jashkenas/underscore/issues/580

### CODE REVIEW

**Comment by jareddlc** [comment]
@dbubs I haven't tried `_.isPlainObject()` but it seems like it should work according to the docs.

**Comment by normanjoyner** [comment]
@jareddlc great catch! I think @dbubs suggestion to use `_.isPlainObject()` is probably the best solution, as we expect options to be passed as an object. We could also keep conditional ordering as is.

**Comment by normanjoyner** [comment]
@jareddlc do you mind implementing `_.isPlainObject()` instead?

**Comment by jareddlc** [comment]
@normanjoyner yup i'll submit a PR later on today.

**Comment by jareddlc** [comment]
Closing and submitted new PR #10

**Comment by normanjoyner** [comment]
@jareddlc if you want to remove the changes in `lib.api.js`, the documentation changes are still quite useful. If not, I will just make the changes myself before drafting the next release.

**Comment by jareddlc** [comment]
yup, I was going to submit a PR for docs soon. I didn't want to submit them together.

**Pull request closed without merging**
